function doBar_emisdep(xvector1, yvector1)
%CREATEFIGURE(XVECTOR1,YVECTOR1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 09-Oct-2011 18:01:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create bar
bar(xvector1,yvector1,'BarWidth',8);

% Create xlabel
xlabel('wavelength (nm)');

% Create ylabel
ylabel('Emission Relative to Full Model');

% Create title
title('Emission Dependence on Included Levels (11 versus 65 levels) (n_e = 10^{11} cm^{-3})');

