function doBar2(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 06-Oct-2011 15:58:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 25]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar(ymatrix1);

