function doBar(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 06-Oct-2011 13:28:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25],...
    'XGrid','on',...
    'Position',[0.13 0.11 0.814908180300501 0.815]);
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 26]);
box(axes1,'on');
hold(axes1,'all');

% Create bar
bar(yvector1);

% Create xlabel
xlabel({'level'});

% Create ylabel
ylabel({'Contribution'});

