function doBar_ratiodep(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 09-Oct-2011 17:00:04

% Create figure
figure1 = figure;
colormap('copper');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(1),'DisplayName','65 Levels');
set(bar1(2),'DisplayName','25 Levels');
set(bar1(3),'DisplayName','19 Levels');
set(bar1(4),'DisplayName','11 Levels');

% Create xlabel
xlabel('Level (i)');

% Create ylabel
ylabel('n_i / n_{10}');

% Create title
title('Population Ratio Dependence on Included Levels (n_e = 10^{11} cm^{-3})');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.600793650793653 0.781277981277981 0.0666666666666667 0.0871794871794872]);

