function doBar_leveldep(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 09-Oct-2011 16:38:15

% Create figure
figure1 = figure;
colormap('copper');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(1),'DisplayName','25 Levels');
set(bar1(2),'DisplayName','19 Levels');
set(bar1(3),'DisplayName','11 Levels');

% Create xlabel
xlabel('Level');

% Create ylabel
ylabel('Population Relative to Full Model');

% Create title
title('Dependence on Included Levels (n_e = 10^6 cm^{-3})');

% Create legend
legend(axes1,'show');

