function plotReducedLevels(xvector1, ymatrix1)
%CREATEFIGURE(XVECTOR1,YMATRIX1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 06-Nov-2011 14:05:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XTick',[6 7 8 9 10 11],'XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',axes1);
set(bar1(1),...
    'FaceColor',[0.23137255012989 0.443137258291245 0.337254911661148],...
    'DisplayName','25 Levels');
set(bar1(2),...
    'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
    'DisplayName','11 Levels');

% Create xlabel
xlabel('Level','FontSize',12);

% Create ylabel
ylabel('Population Relative to Full Model','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',12);

