function plotGainLoss(ymatrix1, yvector1)
%CREATEFIGURE(YMATRIX1,YVECTOR1)
%  YMATRIX1:  bar matrix data
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 06-Nov-2011 13:45:58

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,...
    'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot1,[0 20]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot1,[-1 1]);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'BarLayout','grouped','Parent',subplot1);
set(bar1(1),'FaceColor',[0 0.498039215803146 0]);

% Create xlabel
xlabel({'contributing level'},'FontSize',12);

% Create title
title({'Gain/Loss'},'FontSize',15);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1,...
    'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot2,[0 20]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot2,[-1 1]);
box(subplot2,'on');
hold(subplot2,'all');

% Create bar
bar(yvector1,...
    'FaceColor',[0.0431372560560703 0.517647087574005 0.780392169952393],...
    'Parent',subplot2);

% Create xlabel
xlabel({'contributing level'},'FontSize',12);

% Create title
title({'Net Gain'},'FontSize',15);

