function plotBestFit(xvector1, ymatrix1)
%CREATEFIGURE(XVECTOR1,YMATRIX1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 06-Nov-2011 14:15:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTick',[680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990],...
    'XMinorTick','on');
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[680 990]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',axes1);
set(bar1(1),'FaceColor','none',...
    'EdgeColor',[0.47843137383461 0.062745101749897 0.894117653369904],...
    'DisplayName',' Calculated Best Fit');
set(bar1(2),...
    'FaceColor',[0.47843137383461 0.062745101749897 0.894117653369904],...
    'DisplayName',' Measured');

% Create xlabel
xlabel('wavelength (nm)','FontSize',12);

% Create ylabel
ylabel('emission (s^{-1} cm^{-3})','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.776686507936509 0.841064609149716 0.11547619047619 0.0505494505494506],...
    'FontSize',12);

