function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Oct-2011 11:20:28

% Create figure
figure1 = figure;
colormap('gray');

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'LineStyle','--','DisplayName','n=1');
set(plot1(2),'DisplayName','n=2');

% Create title
title('Population of HeII');

% Create xlabel
xlabel('times (seconds)');

% Create ylabel
ylabel('population (m^{-3})');

% Create legend
legend(axes1,'show');

