function correlation(X1, Y1, S1, C1)
%CREATEFIGURE(X1,Y1,S1,C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 15-Nov-2012 20:51:22

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[1 2 2.6],...
    'XTick',[1000000000000 2000000000000 2800000000000],...
    'FontWeight','bold');
hold(axes1,'all');

% Create scatter
scatter(X1,Y1,S1,C1,'MarkerFaceColor',[0 0 0],'MarkerEdgeColor',[0 0 0]);

% Create xlabel
xlabel('n_{ArI}^{*}','FontWeight','bold','FontSize',15);

% Create ylabel
ylabel('L [W sR^{-1} m^{-2}]','FontWeight','bold','FontSize',15);

% Create title
title('High Pass Correlation','FontWeight','bold','FontSize',20);

% Create textbox
annotation(figure1,'textbox',...
    [0.200413645660414 0.724197807763268 0.448126483383823 0.113972144846797],...
    'String',{'\rho = 0.9971'},...
    'FontWeight','bold',...
    'FontSize',20,...
    'FitBoxToText','off',...
    'LineStyle','none');

