function radial_plot(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-May-2012 22:55:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'Color',[0 0 0]);
set(plot1(1),'LineStyle',':','DisplayName','static');
set(plot1(2),'DisplayName','non-static');

% Create xlabel
xlabel('R (m)','FontSize',20);

% Create ylabel
ylabel('n_8/n_1','FontSize',20);

% Create legend
legend(axes1,'show');

